package classes;

import dados.SalvarLoja;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;
import model.Loja;
import model.LojaCrud;

public class InicioView extends javax.swing.JPanel {

    /**
     * Creates new form InicioView
     */
    public InicioView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textDatetime = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textNomeLoja = new javax.swing.JLabel();
        textCapacidade = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        setLayout(new java.awt.BorderLayout());

        textDatetime.setBackground(new java.awt.Color(255, 166, 77));
        textDatetime.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        textDatetime.setForeground(new java.awt.Color(102, 102, 102));
        textDatetime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textDatetime.setText("hora");
        add(textDatetime, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 166, 77));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/iconeEstoque.png"))); // NOI18N
        jPanel1.add(jLabel4);

        jPanel2.setBackground(new java.awt.Color(255, 166, 77));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        textNomeLoja.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        textNomeLoja.setForeground(new java.awt.Color(255, 255, 255));
        textNomeLoja.setText("Nome Loja");
        jPanel2.add(textNomeLoja);

        textCapacidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textCapacidade.setForeground(new java.awt.Color(255, 255, 255));
        textCapacidade.setText("Capacidade de estoque:");
        jPanel2.add(textCapacidade);

        jPanel1.add(jPanel2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
       mostrarHora();
       mostrarDados();
    }//GEN-LAST:event_formAncestorAdded

    private void mostrarDados() {
        String id_temp = new SalvarLoja().recuperarID();
        int id = Integer.parseInt(id_temp);
        Loja l = new LojaCrud().read(id);
        String capacidade = String.valueOf(l.getCapacidadeEstoque());
        
        textNomeLoja.setText(l.getNomeLoja());
        textCapacidade.setText("Capacidade de estoque: "+capacidade);
       
    }
    
    private void mostrarHora() {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/uuuu")
                .withResolverStyle(ResolverStyle.STRICT);
        
        DateTimeFormatter dtfhour = DateTimeFormatter.ofPattern("HH:mm:ss").withResolverStyle(ResolverStyle.STRICT);
        
        LocalDate dataAtual = LocalDate.now();
        LocalTime horaAtual = LocalTime.now();
        
        String data = dataAtual.format(dtf);
        String hora = horaAtual.format(dtfhour);
        
        textDatetime.setText("Hoje: "+data+" - "+hora);
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textCapacidade;
    private javax.swing.JLabel textDatetime;
    private javax.swing.JLabel textNomeLoja;
    // End of variables declaration//GEN-END:variables
}
