package classes;

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        initBackground();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrograma = new javax.swing.JMenu();
        mniInicio = new javax.swing.JMenuItem();
        mniSair = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        mniVisualizar = new javax.swing.JMenuItem();
        mniAlterar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mniAlterarCapacidade = new javax.swing.JMenuItem();
        mniCategoria = new javax.swing.JMenuItem();
        menuLocal = new javax.swing.JMenu();
        menuFornecedor = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mini estoque");
        setExtendedState(MAXIMIZED_BOTH);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/iconeEstoque.png")).getImage());
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });

        menuPrograma.setText("Programa");

        mniInicio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        mniInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Home.png"))); // NOI18N
        mniInicio.setText("Inicio");
        mniInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniInicioActionPerformed(evt);
            }
        });
        menuPrograma.add(mniInicio);

        mniSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mniSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Sign Public.png"))); // NOI18N
        mniSair.setText("Sair");
        mniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSairActionPerformed(evt);
            }
        });
        menuPrograma.add(mniSair);

        jMenuBar1.add(menuPrograma);

        menuEstoque.setText("Estoque");

        mniVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        mniVisualizar.setText("Visualizar e Pesquisar");
        mniVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVisualizarActionPerformed(evt);
            }
        });
        menuEstoque.add(mniVisualizar);

        mniAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pencil.png"))); // NOI18N
        mniAlterar.setText("Alterar ou remover");
        mniAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlterarActionPerformed(evt);
            }
        });
        menuEstoque.add(mniAlterar);
        menuEstoque.add(jSeparator1);

        mniAlterarCapacidade.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        mniAlterarCapacidade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Box.png"))); // NOI18N
        mniAlterarCapacidade.setText("Alterar capacidade");
        mniAlterarCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAlterarCapacidadeActionPerformed(evt);
            }
        });
        menuEstoque.add(mniAlterarCapacidade);

        mniCategoria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        mniCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Bookmarks 2.png"))); // NOI18N
        mniCategoria.setText("Gerenciar categorias");
        mniCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCategoriaActionPerformed(evt);
            }
        });
        menuEstoque.add(mniCategoria);

        jMenuBar1.add(menuEstoque);

        menuLocal.setText("Loja");

        menuFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Users.png"))); // NOI18N
        menuFornecedor.setText("Fornecedores");
        menuFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFornecedorActionPerformed(evt);
            }
        });
        menuLocal.add(menuFornecedor);

        jMenuItem4.setText("Informações");
        menuLocal.add(jMenuItem4);

        jMenuBar1.add(menuLocal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mniVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVisualizarActionPerformed
        //EstoqueVisualizar e = new EstoqueVisualizar();
        //this.setContentPane(e);
        //this.revalidate();
        Area_estoque e = new Area_estoque();
        this.setContentPane(e);
        this.revalidate();
    }//GEN-LAST:event_mniVisualizarActionPerformed

    private void mniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mniSairActionPerformed

    private void mniInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniInicioActionPerformed
        InicioView i = new InicioView();
        this.setContentPane(i);
        this.revalidate();
    }//GEN-LAST:event_mniInicioActionPerformed

    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void mniAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlterarActionPerformed
        EstoqueAlterar e = new EstoqueAlterar();
        this.setContentPane(e);
        this.revalidate();
    }//GEN-LAST:event_mniAlterarActionPerformed

    private void menuFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFornecedorActionPerformed
        FornecedorView f = new FornecedorView();
        f.setVisible(true);
    }//GEN-LAST:event_menuFornecedorActionPerformed

    private void mniAlterarCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAlterarCapacidadeActionPerformed
        AlterarCapacidade a = new AlterarCapacidade();
        a.setVisible(true);
    }//GEN-LAST:event_mniAlterarCapacidadeActionPerformed

    private void mniCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCategoriaActionPerformed
        GerenciarCategoria c = new GerenciarCategoria();
        c.setVisible(true);
    }//GEN-LAST:event_mniCategoriaActionPerformed

    private void initBackground() {
        InicioView p = new InicioView();
        this.setContentPane(p);
        this.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuFornecedor;
    private javax.swing.JMenu menuLocal;
    private javax.swing.JMenu menuPrograma;
    private javax.swing.JMenuItem mniAlterar;
    private javax.swing.JMenuItem mniAlterarCapacidade;
    private javax.swing.JMenuItem mniCategoria;
    private javax.swing.JMenuItem mniInicio;
    private javax.swing.JMenuItem mniSair;
    private javax.swing.JMenuItem mniVisualizar;
    // End of variables declaration//GEN-END:variables

}
